"""Forgot email in user

Revision ID: 3ad6551a8a4e
Revises: e482d53f265e
Create Date: 2024-01-22 17:05:55.469041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ad6551a8a4e'
down_revision = 'e482d53f265e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.add_column(sa.Column('CompanyEmail', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.drop_column('CompanyEmail')

    # ### end Alembic commands ###
