"""Changed customer a little

Revision ID: 405338fb0767
Revises: 9f6028e036d5
Create Date: 2024-01-12 17:58:30.874483

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '405338fb0767'
down_revision = '9f6028e036d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Customers', schema=None) as batch_op:
        batch_op.alter_column('Streetaddress',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('City',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('Zipcode',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('Country',
               existing_type=mysql.VARCHAR(length=30),
               nullable=True)
        batch_op.alter_column('CountryCode',
               existing_type=mysql.VARCHAR(length=2),
               nullable=True)
        batch_op.alter_column('Birthday',
               existing_type=mysql.DATETIME(),
               nullable=True)
        batch_op.alter_column('Telephone',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
        batch_op.drop_column('TelephoneCountryCode')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('TelephoneCountryCode', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.alter_column('Telephone',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('Birthday',
               existing_type=mysql.DATETIME(),
               nullable=False)
        batch_op.alter_column('CountryCode',
               existing_type=mysql.VARCHAR(length=2),
               nullable=False)
        batch_op.alter_column('Country',
               existing_type=mysql.VARCHAR(length=30),
               nullable=False)
        batch_op.alter_column('Zipcode',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('City',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('Streetaddress',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###
