"""added adminpermission

Revision ID: 5c0cbb080d24
Revises: 92a75c8dc972
Create Date: 2024-02-22 16:45:04.752658

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5c0cbb080d24'
down_revision = '92a75c8dc972'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('AdminPermission', sa.Boolean(), nullable=True))
    op.drop_column('User', 'PlaceholderPermission')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('PlaceholderPermission', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('User', 'AdminPermission')
    # ### end Alembic commands ###
