"""added passwords

Revision ID: 9f6028e036d5
Revises: 419b5b46d236
Create Date: 2024-01-12 16:58:38.021163

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9f6028e036d5'
down_revision = '419b5b46d236'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('PersonalNumber', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('Password', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('Role', sa.String(length=10), nullable=True))
        batch_op.drop_column('NationalId')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('NationalId', mysql.VARCHAR(length=20), nullable=False))
        batch_op.drop_column('Role')
        batch_op.drop_column('Password')
        batch_op.drop_column('PersonalNumber')

    # ### end Alembic commands ###
