"""Added user and changes

Revision ID: e482d53f265e
Revises: 1d071b174a3e
Create Date: 2024-01-22 16:54:13.951926

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e482d53f265e'
down_revision = '1d071b174a3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Username', sa.String(length=50), nullable=True),
    sa.Column('Password', sa.String(length=50), nullable=True),
    sa.Column('FirstName', sa.String(length=50), nullable=True),
    sa.Column('LastName', sa.String(length=50), nullable=True),
    sa.Column('Role', sa.String(length=50), nullable=True),
    sa.Column('InformationPermission', sa.Boolean(), nullable=True),
    sa.Column('ManagementPermission', sa.Boolean(), nullable=True),
    sa.Column('PlaceholderPermission', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    with op.batch_alter_table('Customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('TelephoneCountryCode', sa.String(length=20), nullable=True))
        batch_op.drop_column('Role')
        batch_op.drop_column('Password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Password', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('Role', mysql.VARCHAR(length=10), nullable=True))
        batch_op.drop_column('TelephoneCountryCode')

    op.drop_table('User')
    # ### end Alembic commands ###
